# Lint directives.
lint:
  # Linter rules.
  # Run `protolint list` to see all available rules.
  rules:
    # Determines whether or not to include the default set of linters.
    no_default: true

    # The specific linters to add.
    add:
      - FIELD_NAMES_LOWER_SNAKE_CASE
      - FILE_NAMES_LOWER_SNAKE_CASE
      - IMPORTS_SORTED
      - INDENT
      - MAX_LINE_LENGTH
      - MESSAGE_NAMES_UPPER_CAMEL_CASE
      - ORDER
      - PACKAGE_NAME_LOWER_CASE
      - PROTO3_FIELDS_AVOID_REQUIRED
      - PROTO3_GROUPS_AVOID
      - REPEATED_FIELD_NAMES_PLURALIZED
      - RPC_NAMES_UPPER_CAMEL_CASE
      - SERVICE_NAMES_END_WITH
      - SYNTAX_CONSISTENT

    # The specific linters to remove.
    remove:
      - ENUM_FIELDS_HAVE_COMMENT
      - ENUMS_HAVE_COMMENT
      - FIELDS_HAVE_COMMENT
      - FIELD_NAMES_EXCLUDE_PREPOSITIONS
      - MESSAGES_HAVE_COMMENT
      - MESSAGE_NAMES_EXCLUDE_PREPOSITIONS
      - RPCS_HAVE_COMMENT
      - SERVICES_HAVE_COMMENT

  # Linter rules option.
  rules_option:
    # MAX_LINE_LENGTH rule option.
    max_line_length:
      # Enforces a maximum line length
      max_chars: 132
      # Specifies the character count for tab characters
      tab_chars: 2

    # INDENT rule option.
    indent:
      # Available styles are 4(4-spaces), 2(2-spaces) or tab.
      style: 2
      # Available newlines are "\n", "\r", or "\r\n".
      newline: "\n"
      # Specifies if it should stop considering and inserting new lines at the appropriate positions
      # when the inner elements are on the same line. Default is false.
      not_insert_newline: true